<?xml version="1.0" encoding="EUC-KR"?>		
<SABANG_ORDER_LIST>		
	<HEADER>	
		<SEND_COMPAYNY_ID>{{config('sabangnet.SEND_COMPAYNY_ID')}}</SEND_COMPAYNY_ID>
		<SEND_AUTH_KEY>{{config('sabangnet.SEND_AUTH_KEY')}}</SEND_AUTH_KEY>
		<SEND_DATE>{{config('sabangnet.SEND_DATE')}}</SEND_DATE>
	</HEADER>
	<DATA>
		<ORD_ST_DATE>{{$ORD_ST_DATE}}</ORD_ST_DATE>
		<ORD_ED_DATE>{{$ORD_ED_DATE}}</ORD_ED_DATE>
		<ORD_FIELD><![CDATA[{{$ORD_FIELD}}]]></ORD_FIELD>

		<JUNG_CHK_YN2>{{$JUNG_CHK_YN2}}</JUNG_CHK_YN2>
		<ORDER_ID>{{$ORDER_ID}}</ORDER_ID>
		<MALL_ID>{{$MALL_ID}}</MALL_ID>
		<ORDER_STATUS>{{$ORDER_STATUS}}</ORDER_STATUS>
		<LANG>{{$LANG}}</LANG>
		<PARTNER_ID>{{$PARTNER_ID}}</PARTNER_ID>
		<MALL_USER_ID>{{$MALL_USER_ID}}</MALL_USER_ID>
		<DPARTNER_ID>{{$DPARTNER_ID}}</DPARTNER_ID>
	</DATA>	
</SABANG_ORDER_LIST>